### ISSUE TITLE
Opentherm installation fails

### ISSUE THREAD

**Issue by louisvangeldrop** [DrozmotiX/ioBroker.opentherm#344]
npm install iobroker.opentherm@0.1.9 --loglevel error --prefix "/opt/iobroker" (System call)

npm ERR! code 1

npm ERR! path /opt/iobroker/node_modules/iobroker.opentherm/node_modules/@serialport/bindings

npm ERR! command failed

npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuildnpm ERR! make: Entering directory '/opt/iobroker/node_modules/iobroker.opentherm/node_modules/@serialport/bindings/build'npm ERR! CXX(target) Release/obj.target/bindings/src/serialport.o

npm ERR! make: Leaving directory '/opt/iobroker/node_modules/iobroker.opentherm/node_modules/@serialport/bindings/build'npm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:78:51: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]

npm ERR! 78 | uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:135:53: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 135 | uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:175:52: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 175 | uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:215:52: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 215 | uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:270:50: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 270 | uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:314:50: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 314 | uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:npm ERR! ../src/serialport.cpp:329:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’npm ERR! 329 | results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));npm ERR! | ^npm ERR! In file included from /home/iobroker/.cache/node-gyp/16.13.1/include/node/node.h:63,npm ERR! from ../../../../../nan/nan.h:58,npm ERR! from ../src/./serialport.h:6,npm ERR! from ../src/serialport.cpp:1:npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’npm ERR! 3961 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate expects 3 arguments, 2 providednpm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’npm ERR! 3964 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate expects 3 arguments, 2 providednpm ERR! ../src/serialport.cpp:330:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’npm ERR! 330 | results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));npm ERR! | ^npm ERR! In file included from /home/iobroker/.cache/node-gyp/16.13.1/include/node/node.h:63,npm ERR! from ../../../../../nan/nan.h:58,npm ERR! from ../src/./serialport.h:6,npm ERR! from ../src/serialport.cpp:1:npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’npm ERR! 3961 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate expects 3 arguments, 2 providednpm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’npm ERR! 3964 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate expects 3 arguments, 2 providednpm ERR! ../src/serialport.cpp:331:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’npm ERR! 331 | results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));npm ERR! | ^npm ERR! In file included from /home/iobroker/.cache/node-gyp/16.13.1/include/node/node.h:63,npm ERR! from ../../../../../nan/nan.h:58,npm ERR! from ../src/./serialport.h:6,npm ERR! from ../src/serialport.cpp:1:npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’npm ERR! 3961 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,npm ERR! | ^~~

npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate expects 3 arguments, 2 providednpm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’npm ERR! 3964 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate expects 3 arguments, 2 providednpm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:npm ERR! ../src/serialport.cpp:363:58: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 363 | uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:npm ERR! ../src/serialport.cpp:378:106: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’npm ERR! 378 | results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));npm ERR! | ^npm ERR! In file included from /home/iobroker/.cache/node-gyp/16.13.1/include/node/node.h:63,npm ERR! from ../../../../../nan/nan.h:58,npm ERR! from ../src/./serialport.h:6,npm ERR! from ../src/serialport.cpp:1:npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’npm ERR! 3961 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3961:37: note: candidate expects 3 arguments, 2 providednpm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’npm ERR! 3964 | V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,npm ERR! | ^~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/v8.h:3964:37: note: candidate expects 3 arguments, 2 providednpm ERR! ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:

npm ERR! ../src/serialport.cpp:409:52: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]npm ERR! 409 | uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! ../src/serialport.cpp: At global scope:npm ERR! ../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses]npm ERR! 430 | SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {npm ERR! | ^npm ERR! ../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses]npm ERR! 449 | SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {npm ERR! | ^npm ERR! In file included from ../../../../../nan/nan.h:58,npm ERR! from ../src/./serialport.h:6,npm ERR! from ../src/serialport.cpp:1:npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/node.h:821:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]npm ERR! 821 | (node::addon_register_func) (regfunc), \npm ERR! | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~npm ERR! /home/iobroker/.cache/node-gyp/16.13.1/include/node/node.h:855:3: note: in expansion of macro ‘NODE_MODULE_X’npm ERR! 855 | NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage)npm ERR! | ^~~~~~~~~~~~~npm ERR! ../src/serialport.cpp:483:1: note: in expansion of macro ‘NODE_MODULE’npm ERR! 483 | NODE_MODULE(serialport, init);npm ERR! | ^~~~~~~~~~~npm ERR! make: *** [bindings.target.mk:114: Release/obj.target/bindings/src/serialport.o] Error 1npm ERR! gyp ERR! build error npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2npm ERR! gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:390:28)npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)npm ERR! gyp ERR! System Linux 5.10.63-v7l+npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/iobroker.opentherm/node_modules/@serialport/bindingsnpm ERR! gyp ERR! node -v v16.13.1npm ERR! gyp ERR! node-gyp -v v8.3.0npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-12-17T10_58_21_577Z-debug.log

host.raspberrypi4 Cannot install iobroker.opentherm@0.1.9: 1

ERROR: Process exited with code 25

**Comment by abodewits** [comment]
having the same problem installing the adapter in iobroker

$ iobroker add opentherm auto --host Nuc-iobroker

NPM version: 6.14.15

npm install iobroker.opentherm@0.1.9 --loglevel error --prefix "/opt/iobroker" (System call)

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:

../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen); ^~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate); ^~~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose); ^~~~~~~~~~~~~~../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush); ^~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:270:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet); ^~~~~~~~~~~~

../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:314:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet); ^~~~~~~~~~~~../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:../src/serialport.cpp:329:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’ results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts)); ^In file included from /home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’

V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided../src/serialport.cpp:330:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’ results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr)); ^In file included from /home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided../src/serialport.cpp:331:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’

results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd)); ^In file included from /home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:363:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate); ^~~~~~~~~~~~~~~~~~~~

../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:../src/serialport.cpp:378:106: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’ results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate)); ^In file included from /home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:67, from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3670:37: note: candidate expects 3 arguments, 2 provided/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’ V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index, ^~~/home/iobroker/.cache/node-gyp/14.18.2/include/node/v8.h:3673:37: note: candidate expects 3 arguments, 2 provided../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type] uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain); ^~~~~~~~~~~~~~

../src/serialport.cpp: At global scope:../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses] SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) { ^../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses] SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) { ^

In file included from ../../../../../nan/nan.h:56, from ../src/./serialport.h:6, from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:787:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type] (node::addon_register_func) (regfunc), \ ^/home/iobroker/.cache/node-gyp/14.18.2/include/node/node.h:821:3: note: in expansion of macro ‘NODE_MODULE_X’ NODE_MODULE_X(modname, regfunc, NULL, 0) // NOLINT (readability/null_usage) ^~~~~~~~~~~~~../src/serialport.cpp:483:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~

make: *** [bindings.target.mk:114: Release/obj.target/bindings/src/serialport.o] Fout 1gyp ERR! build error

gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack at ChildProcess.emit (events.js:400:28)gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)gyp ERR! System Linux 4.19.0-18-amd64gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/iobroker.opentherm/node_modules/@serialport/bindingsgyp ERR! node -v v14.18.2gyp ERR! node-gyp -v v5.1.0gyp ERR! not ok

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`

npm ERR! Exit status 1npm ERR!

npm ERR! Failed at the @serialport/bindings@2.0.8 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR! /home/iobroker/.npm/_logs/2021-12-21T19_42_37_983Z-debug.log

host.Nuc-iobroker Cannot install iobroker.opentherm@0.1.9: 1

ERROR: Process exited with code 25

**Comment by DutchmanNL** [comment]
solved in v0.2.5
